In [1]:
# Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np

# Create a NumPy array of integers from 0 to 5
arr = np.arange(6)

# Print the array and its data type
arr, arr.dtype

(array([0, 1, 2, 3, 4, 5]), dtype('int32'))

In [2]:
# Given a NumPy array 'arr', check if its data type is float64.
# Define the array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
is_float64 = arr.dtype == np.float64

is_float64

True

In [3]:
# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Display the array and its data type
arr, arr.dtype

(array([1.+2.j, 3.+4.j, 5.+6.j]), dtype('complex128'))

In [4]:
# Convert an existing NumPy array 'arr' of integers to float32 data type.
# Original NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert to float32
arr_float32 = arr.astype(np.float32)

# Display the converted array and its data type
print(arr_float32)
print(arr_float32.dtype)

[1. 2. 3. 4. 5.]
float32


In [5]:
# Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
# Define a NumPy array with float64 data type
arr = np.array([1.123456789, 2.987654321, 3.456789123], dtype=np.float64)

# Convert the array to float32 to reduce decimal precision
arr_float32 = arr.astype(np.float32)

# Display the original and converted arrays along with their data types
arr, arr.dtype, arr_float32, arr_float32.dtype

(array([1.12345679, 2.98765432, 3.45678912]),
 dtype('float64'),
 array([1.1234568, 2.9876542, 3.456789 ], dtype=float32),
 dtype('float32'))

In [6]:
# Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    """
    Returns the shape, size, and data type of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): The input array.
    
    Returns:
        tuple: A tuple containing the shape, size, and data type of the array.
    """
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

# Example usage
if __name__ == "__main__":
    array = np.array([[1, 2, 3], [4, 5, 6]])
    attributes = array_attributes(array)
    print(f"Shape: {attributes[0]}, Size: {attributes[1]}, Data Type: {attributes[2]}")

Shape: (2, 3), Size: 6, Data Type: int32


In [7]:
# Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    """
    Returns the dimensionality of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): The input array.
    
    Returns:
        int: The dimensionality of the array (number of axes).
    """
    return arr.ndim

# Example usage
if __name__ == "__main__":
    array = np.array([[1, 2, 3], [4, 5, 6]])
    dimension = array_dimension(array)
    print(f"The dimensionality of the array is: {dimension}")

The dimensionality of the array is: 2


In [8]:
# Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def array_dimension(arr):
    """
    Returns the dimensionality of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): The input array.
    
    Returns:
        int: The number of dimensions of the array.
    """
    return arr.ndim

# Example usage
if __name__ == "__main__":
    array = np.array([[1, 2, 3], [4, 5, 6]])
    dimension = array_dimension(array)
    print(f"Dimensionality: {dimension}")

Dimensionality: 2


In [9]:
# Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    """
    Returns the strides of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): The input array.
    
    Returns:
        tuple: The strides of the array.
    """
    return arr.strides

# Example usage
if __name__ == "__main__":
    array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
    strides = array_strides(array)
    print(f"Strides: {strides}")

Strides: (12, 4)


In [10]:
# Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    """
    Returns the shape and strides of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): The input array.
    
    Returns:
        tuple: A tuple containing the shape and strides of the array.
    """
    shape = arr.shape
    strides = arr.strides
    return shape, strides

# Example usage
if __name__ == "__main__":
    array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
    shape, strides = shape_stride_relationship(array)
    print(f"Shape: {shape}, Strides: {strides}")

Shape: (2, 3), Strides: (12, 4)


In [11]:
# Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    """
    Creates a NumPy array of zeros with n elements.
    
    Parameters:
        n (int): The number of elements in the array.
    
    Returns:
        numpy.ndarray: A NumPy array of zeros with n elements.
    """
    return np.zeros(n)

# Example usage
if __name__ == "__main__":
    n = 5
    zeros_array = create_zeros_array(n)
    print(f"Array of zeros with {n} elements: {zeros_array}")

Array of zeros with 5 elements: [0. 0. 0. 0. 0.]


In [12]:
# Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(rows, cols):
    """
    Creates a 2D NumPy array filled with ones of size rows x cols.
    
    Parameters:
        rows (int): The number of rows in the array.
        cols (int): The number of columns in the array.
    
    Returns:
        numpy.ndarray: A 2D NumPy array filled with ones.
    """
    return np.ones((rows, cols))

# Example usage
if __name__ == "__main__":
    rows = 3
    cols = 4
    ones_matrix = create_ones_matrix(rows, cols)
    print(f"Matrix of ones with size {rows}x{cols}:\n{ones_matrix}")

Matrix of ones with size 3x4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(start, stop, step):
    """
    Creates a NumPy array with a range starting from `start`,
    ending at `stop` (exclusive), and with the specified `step`.
    
    Parameters:
        start (int): The starting value of the range.
        stop (int): The end value of the range (exclusive).
        step (int): The step size.
    
    Returns:
        numpy.ndarray: A NumPy array containing the range of values.
    """
    return np.arange(start, stop, step)

# Example usage
if __name__ == "__main__":
    start = 1
    stop = 10
    step = 2
    range_array = generate_range_array(start, stop, step)
    print(f"Range array from {start} to {stop} with step {step}: {range_array}")

Range array from 1 to 10 with step 2: [1 3 5 7 9]


In [14]:
# Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start, stop, num):
    """
    Generates a NumPy array with `num` equally spaced values between 
    `start` and `stop` (inclusive).
    
    Parameters:
        start (float): The starting value of the range.
        stop (float): The end value of the range (inclusive).
        num (int): The number of equally spaced values to generate.
    
    Returns:
        numpy.ndarray: A NumPy array with the specified range and spacing.
    """
    return np.linspace(start, stop, num)

# Example usage
if __name__ == "__main__":
    start = 0.0
    stop = 1.0
    num = 5
    linear_space_array = generate_linear_space(start, stop, num)
    print(f"{num} equally spaced values between {start} and {stop}:\n{linear_space_array}")

5 equally spaced values between 0.0 and 1.0:
[0.   0.25 0.5  0.75 1.  ]


In [15]:
# Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    """
    Creates a square identity matrix of size n x n using numpy.eye.
    
    Parameters:
        n (int): The size of the identity matrix.
    
    Returns:
        numpy.ndarray: An n x n identity matrix.
    """
    return np.eye(n)

# Example usage
if __name__ == "__main__":
    n = 4
    identity_matrix = create_identity_matrix(n)
    print(f"Identity matrix of size {n}x{n}:\n{identity_matrix}")

Identity matrix of size 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# Write a function that takes a Python list and converts it into a NumPy array.
def list_to_numpy_array(input_list):
    """
    Converts a Python list into a NumPy array.
    
    Parameters:
        input_list (list): The Python list to be converted.
    
    Returns:
        numpy.ndarray: A NumPy array representation of the input list.
    """
    return np.array(input_list)

# Example usage
if __name__ == "__main__":
    python_list = [1, 2, 3, 4, 5]
    numpy_array = list_to_numpy_array(python_list)
    print(f"Original list: {python_list}")
    print(f"Converted NumPy array: {numpy_array}")

Original list: [1, 2, 3, 4, 5]
Converted NumPy array: [1 2 3 4 5]


In [17]:
# Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Create a view of the original array
view_array = original_array.view()

# Modify the view and observe changes in the original array
view_array[0] = 10

# Output the results
print("Original array:", original_array)
print("View array:", view_array)
print(f"Are original_array and view_array the same object? {original_array is view_array}")
print(f"Do original_array and view_array share the same data? {np.may_share_memory(original_array, view_array)}")

Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]
Are original_array and view_array the same object? False
Do original_array and view_array share the same data? True


In [18]:
# Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(array1, array2, axis=0):
    """
    Concatenates two NumPy arrays along the specified axis.
    
    Parameters:
        array1 (numpy.ndarray): The first array.
        array2 (numpy.ndarray): The second array.
        axis (int): The axis along which to concatenate. Default is 0.
    
    Returns:
        numpy.ndarray: The concatenated array.
    """
    return np.concatenate((array1, array2), axis=axis)

# Example usage
if __name__ == "__main__":
    array1 = np.array([[1, 2], [3, 4]])
    array2 = np.array([[5, 6], [7, 8]])
    
    concatenated_array = concatenate_arrays(array1, array2, axis=0)
    print("Concatenated along axis 0:\n", concatenated_array)

    concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
    print("Concatenated along axis 1:\n", concatenated_array_axis1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [19]:
# Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6, 7], [8, 9, 10]])

# Concatenate the arrays horizontally (along axis 1)
concatenated_array = np.concatenate((array1, array2), axis=1)

# Output the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated Array (along axis 1):\n", concatenated_array)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[ 5  6  7]
 [ 8  9 10]]
Concatenated Array (along axis 1):
 [[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


In [20]:
# Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack_arrays(arrays_list):
    """
    Vertically stacks multiple NumPy arrays provided as a list.
    
    Parameters:
        arrays_list (list of numpy.ndarray): List of NumPy arrays to be stacked.
    
    Returns:
        numpy.ndarray: The vertically stacked array.
    """
    return np.vstack(arrays_list)

# Example usage
if __name__ == "__main__":
    array1 = np.array([[1, 2], [3, 4]])
    array2 = np.array([[5, 6], [7, 8]])
    array3 = np.array([[9, 10], [11, 12]])

    arrays = [array1, array2, array3]
    stacked_array = vertical_stack_arrays(arrays)
    
    print("Stacked array:\n", stacked_array)

Stacked array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [21]:
# Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_range_array(start, stop, step):
    """
    Creates an array of integers within the specified range (inclusive)
    with a given step size.
    
    Parameters:
        start (int): The starting value of the range.
        stop (int): The end value of the range (inclusive).
        step (int): The step size between the values.
    
    Returns:
        numpy.ndarray: A NumPy array with the specified range and step.
    """
    return np.arange(start, stop + 1, step)

# Example usage
if __name__ == "__main__":
    start = 1
    stop = 10
    step = 2
    
    range_array = create_range_array(start, stop, step)
    print(f"Array from {start} to {stop} with step {step}: {range_array}")

Array from 1 to 10 with step 2: [1 3 5 7 9]


In [22]:
# Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate_equally_spaced_values():
    """
    Generates an array of 10 equally spaced values between 0 and 1 (inclusive).
    
    Returns:
        numpy.ndarray: A NumPy array of 10 equally spaced values between 0 and 1.
    """
    return np.linspace(0, 1, 10)

# Example usage
if __name__ == "__main__":
    equally_spaced_values = generate_equally_spaced_values()
    print(f"Equally spaced values between 0 and 1: {equally_spaced_values}")

Equally spaced values between 0 and 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def generate_log_spaced_values():
    """
    Generates an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
    
    Returns:
        numpy.ndarray: A NumPy array of 5 logarithmically spaced values between 1 and 1000.
    """
    return np.logspace(np.log10(1), np.log10(1000), 5)

# Example usage
if __name__ == "__main__":
    log_spaced_values = generate_log_spaced_values()
    print(f"Logarithmically spaced values between 1 and 1000: {log_spaced_values}")

Logarithmically spaced values between 1 and 1000: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd
# Generate a NumPy array with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(random_array, columns=["Column 1", "Column 2", "Column 3"])

# Display the DataFrame
print(df)

   Column 1  Column 2  Column 3
0        82         3        69
1        71        50        35
2        96        55        50
3         1        81        69
4        68        19        99


In [25]:
# Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negative_with_zero(df, column_name):
    """
    Replaces all negative values in a specific column with zeros using NumPy operations.
    
    Parameters:
        df (pandas.DataFrame): The DataFrame.
        column_name (str): The name of the column where negative values should be replaced.
    
    Returns:
        pandas.DataFrame: The updated DataFrame.
    """
    # Using NumPy's where function to replace negative values with zeros
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
if __name__ == "__main__":
    # Sample DataFrame with negative values
    data = {
        "Column 1": [10, -5, 30, -2, 50],
        "Column 2": [20, 25, -5, 15, -10]
    }
    
    df = pd.DataFrame(data)
    
    print("Original DataFrame:\n", df)
    
    # Replace negative values in 'Column 1' with zero
    df_updated = replace_negative_with_zero(df, "Column 1")
    
    print("\nUpdated DataFrame:\n", df_updated)

Original DataFrame:
    Column 1  Column 2
0        10        20
1        -5        25
2        30        -5
3        -2        15
4        50       -10

Updated DataFrame:
    Column 1  Column 2
0        10        20
1         0        25
2        30        -5
3         0        15
4        50       -10


In [26]:
# Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50])
# Define the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

# Output the 3rd element
print("The 3rd element is:", third_element)

The 3rd element is: 30


In [27]:
# Retrieve the element at index (1, 2) from the 2D NumPy array.
# Define the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

# Output the element
print("The element at index (1, 2) is:", element)

The element at index (1, 2) is: 6


In [28]:
# Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# Define the NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Extract elements greater than 5 using boolean indexing
filtered_elements = arr[arr > 5]

# Output the filtered elements
print("Elements greater than 5:", filtered_elements)

Elements greater than 5: [ 8 10  7]


In [29]:
# Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
# Define the NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_elements = arr[2:6]

# Output the sliced elements
print("Extracted elements from index 2 to 5:", sliced_elements)

Extracted elements from index 2 to 5: [3 4 5 6]


In [30]:
# Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
# Define the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

# Output the extracted sub-array
print("Extracted sub-array:")
print(sub_array)

Extracted sub-array:
[[2 3]
 [5 6]]


In [31]:
# Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements_by_indices(array_2d, indices):
    """
    Extract elements from a 2D array based on indices provided in another array.
    
    Parameters:
    - array_2d (np.ndarray): The input 2D NumPy array.
    - indices (list of tuples): List of tuples representing row and column indices.
    
    Returns:
    - np.ndarray: A 1D array of extracted elements in the specified order.
    """
    return np.array([array_2d[row, col] for row, col in indices])
# Define the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Define the indices to extract
indices = [(0, 1), (1, 2), (2, 0)]

# Extract elements using the function
extracted_elements = extract_elements_by_indices(arr_2d, indices)

# Output the result
print("Extracted elements:", extracted_elements)

Extracted elements: [2 6 7]


In [32]:
# Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_greater_than_threshold(array_1d, threshold):
    """
    Filters elements greater than a given threshold from a 1D array using boolean indexing.
    
    Parameters:
    - array_1d (np.ndarray): The input 1D NumPy array.
    - threshold (int or float): The threshold value.
    
    Returns:
    - np.ndarray: A new array containing elements greater than the threshold.
    """
    return array_1d[array_1d > threshold]
# Define the 1D NumPy array
arr_1d = np.array([10, 5, 20, 15, 2, 25])

# Define the threshold value
threshold = 15

# Filter elements greater than the threshold
filtered_array = filter_greater_than_threshold(arr_1d, threshold)

# Output the result
print("Filtered elements greater than", threshold, ":", filtered_array)


Filtered elements greater than 15 : [20 25]


In [35]:
# Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elements_from_3d(array_3d, indices_x, indices_y, indices_z):
    """
    Extracts specific elements from a 3D NumPy array based on indices from three separate arrays.
    
    Parameters:
    - array_3d (np.ndarray): The input 3D NumPy array.
    - indices_x (np.ndarray): Array of indices for the first dimension.
    - indices_y (np.ndarray): Array of indices for the second dimension.
    - indices_z (np.ndarray): Array of indices for the third dimension.
    
    Returns:
    - np.ndarray: Array of extracted elements.
    """
    return array_3d[indices_x, indices_y, indices_z]
# Define a 3D NumPy array
array_3d = np.array([[[ 1,  2,  3], 
                    [ 4,  5,  6], 
                    [ 7,  8,  9]],
                   [[10, 11, 12], 
                    [13, 14, 15], 
                    [16, 17, 18]],
                   [[19, 20, 21], 
                    [22, 23, 24],
                    [25, 26, 27]]])

# Define the indices for each dimension
indices_x = np.array([0, 1, 2])
indices_y = np.array([1, 2, 0])
indices_z = np.array([2, 1, 0])

# Extract elements using the function
extracted_elements = extract_elements_from_3d(array_3d, indices_x, indices_y, indices_z)

# Output the result
print("Extracted elements:", extracted_elements)


Extracted elements: [ 6 17 19]


In [36]:
# Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def filter_elements_with_conditions(array, condition1, condition2):
    """
    Filters elements from a NumPy array where both conditions are satisfied.
    
    Parameters:
    - array (np.ndarray): The input NumPy array.
    - condition1 (callable): A function representing the first condition.
    - condition2 (callable): A function representing the second condition.
    
    Returns:
    - np.ndarray: Array of elements satisfying both conditions.
    """
    # Combine conditions using logical AND
    mask = condition1(array) & condition2(array)
    return array[mask]
# Define an array
arr = np.array([10, 15, 20, 25, 30, 35, 40])

# Define two conditions
# Condition 1: Elements should be greater than 20
condition1 = lambda x: x > 20
# Condition 2: Elements should be divisible by 5
condition2 = lambda x: x % 5 == 0

# Apply the function
filtered_elements = filter_elements_with_conditions(arr, condition1, condition2)

# Output the result
print("Filtered elements:", filtered_elements)


Filtered elements: [25 30 35 40]


In [37]:
# Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements_by_indices(arr, row_indices, col_indices):
    """
    Extracts elements from a 2D array using row and column indices.

    Parameters:
    - arr (np.ndarray): The input 2D array.
    - row_indices (np.ndarray): Array of row indices.
    - col_indices (np.ndarray): Array of column indices.

    Returns:
    - np.ndarray: An array of elements corresponding to the specified indices.
    """
    if len(row_indices) != len(col_indices):
        raise ValueError("Row and column indices arrays must have the same length.")
    
    # Extract elements using advanced indexing
    extracted_elements = arr[row_indices, col_indices]
    return extracted_elements
# Define a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Define row and column indices
row_indices = np.array([0, 1, 2])  # Rows: 0, 1, 2
col_indices = np.array([1, 0, 2])  # Columns: 1, 0, 2

# Extract elements
elements = extract_elements_by_indices(arr, row_indices, col_indices)

# Output the result
print("Extracted elements:", elements)


Extracted elements: [2 4 9]


In [38]:
# Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add scalar value of 5 using broadcasting
result = arr + 5

# Output the original and updated arrays
print("Original array:\n", arr)
print("Updated array:\n", result)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Updated array:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [39]:
# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
# Define the arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Multiply each row of arr2 by the corresponding element of arr1 using broadcasting
result = arr1.T * arr2

# Output the arrays and the result
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result:\n", result)

arr1:
 [[2 3 4]]
arr2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Result:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [40]:
# Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
# Define the arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30], 
                 [40, 50, 60], 
                 [70, 80, 90], 
                 [100, 110, 120]])  # Shape (4, 3)

# Add arr1 to each row of arr2 using broadcasting
result = arr2 + arr1.T

# Output the arrays and the result
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result:\n", result)

arr1:
 [[1 2 3 4]]
arr2:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Result:
 [[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [41]:
# Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
# Define the arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[10, 20, 30]])   # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

# Output the arrays and the result
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result:\n", result)

arr1:
 [[1]
 [2]
 [3]]
arr2:
 [[10 20 30]]
Result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [42]:
# Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
# Define the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[10, 20],
                 [30, 40]])   # Shape (2, 2)

# Reshape arr2 to align dimensions
reshaped_arr2 = arr2[:, :1]  # Select the first column and reshape to (2, 1)

# Multiply the arrays using broadcasting
result = arr1 * reshaped_arr2

# Output the arrays and the result
print("arr1:\n", arr1)
print("reshaped_arr2:\n", reshaped_arr2)
print("Result:\n", result)

arr1:
 [[1 2 3]
 [4 5 6]]
reshaped_arr2:
 [[10]
 [30]]
Result:
 [[ 10  20  30]
 [120 150 180]]


In [43]:
# Calculate column wise mean for the given array:
# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_mean = np.mean(arr, axis=0)

# Print the result
print("Column-wise Mean:", column_mean)

Column-wise Mean: [2.5 3.5 4.5]


In [44]:
# Find maximum value in each row of the given array:
# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
row_max = np.max(arr, axis=1)

# Print the result
print("Maximum values in each row:", row_max)

Maximum values in each row: [3 6]


In [45]:
# For the given array, find indices of maximum value in each column.
# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the indices of the maximum value in each column
indices = np.argmax(arr, axis=0)

# Print the result
print("Indices of maximum values in each column:", indices)

Indices of maximum values in each column: [1 1 1]


In [46]:
# For the given array, apply custom function to calculate moving sum along rows.
# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Define the custom function for calculating moving sum
def moving_sum(arr):
    return np.cumsum(arr)

# Apply the moving sum along rows (axis=1)
moving_sum_result = np.apply_along_axis(moving_sum, axis=1, arr=arr)

# Print the result
print("Moving sum along rows:\n", moving_sum_result)

Moving sum along rows:
 [[ 1  3  6]
 [ 4  9 15]]


In [47]:
# In the given array, check if all elements in each column are even.
# Define the array
arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in each column are even
all_even_per_column = np.all(arr % 2 == 0, axis=0)

# Print the result
print("All elements in each column are even:", all_even_per_column)

All elements in each column are even: [False False False]


In [48]:
# Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define the desired shape (m rows, n columns)
m, n = 2, 3

# Reshape the array into a matrix of dimensions (m, n)
reshaped_array = original_array.reshape(m, n)

# Print the reshaped matrix
print("Reshaped Matrix:\n", reshaped_array)

Reshaped Matrix:
 [[1 2 3]
 [4 5 6]]


In [49]:
# Create a function that takes a matrix as input and returns the flattened array.
# Function to flatten the input matrix
def flatten_matrix(matrix):
    return matrix.flatten()

# Define the input matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Call the function to flatten the matrix
flattened_array = flatten_matrix(input_matrix)

# Print the flattened array
print("Flattened Array:", flattened_array)

Flattened Array: [1 2 3 4 5 6]


In [50]:
# Write a function that concatenates two given arrays along a specified axis.
# Function to concatenate two arrays along a specified axis
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

# Define the arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate arrays along axis 0 (row-wise)
concatenated_array_rows = concatenate_arrays(array1, array2, axis=0)

# Concatenate arrays along axis 1 (column-wise)
concatenated_array_columns = concatenate_arrays(array1, array2, axis=1)

# Print the results
print("Concatenated along axis 0 (rows):\n", concatenated_array_rows)
print("Concatenated along axis 1 (columns):\n", concatenated_array_columns)

Concatenated along axis 0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1 (columns):
 [[1 2 5 6]
 [3 4 7 8]]


In [51]:
# Create a function that splits an array into multiple sub-arrays along a specified axis.
# Function to split an array into multiple sub-arrays along a specified axis
def split_array(array, num_splits, axis):
    return np.split(array, num_splits, axis=axis)

# Define the original array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split the array along axis 0 (rows) into 3 sub-arrays
split_array_rows = split_array(original_array, 3, axis=0)

# Split the array along axis 1 (columns) into 3 sub-arrays
split_array_columns = split_array(original_array, 3, axis=1)

# Print the results
print("Split along axis 0 (rows):")
for sub_array in split_array_rows:
    print(sub_array)

print("\nSplit along axis 1 (columns):")
for sub_array in split_array_columns:
    print(sub_array)


Split along axis 0 (rows):
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1 (columns):
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [52]:
# Write a function that inserts and then deletes elements from a given array at specified indices.
# Function to insert and delete elements from an array at specified indices
def insert_and_delete(array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at the specified indices
    array = np.insert(array, indices_to_insert, values_to_insert)
    
    # Delete elements at the specified indices
    array = np.delete(array, indices_to_delete)
    
    return array

# Given original array
original_array = np.array([1, 2, 3, 4, 5])

# Indices and values to insert
indices_to_insert = [2, 4]
values_to_insert = [10, 11]

# Indices to delete
indices_to_delete = [1, 3]

# Call the function
result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

# Print the resulting array
print("Resulting array after insertions and deletions:")
print(result)

Resulting array after insertions and deletions:
[ 1 10  4 11  5]


In [53]:
# Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
# Create arr1 with random integers of shape (3,)
arr1 = np.random.randint(1, 20, size=3)  # Random integers between 1 and 20

# Create arr2 with integers from 1 to 10
arr2 = np.array([1, 2, 3])

# Perform element-wise addition
result = arr1 + arr2

# Print the arrays and their result
print("Array 1 (random integers):", arr1)
print("Array 2 (integers from 1 to 3):", arr2)
print("Result of element-wise addition:", result)

Array 1 (random integers): [15 12  2]
Array 2 (integers from 1 to 3): [1 2 3]
Result of element-wise addition: [16 14  5]


In [54]:
# Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
# Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Perform element-wise subtraction
result = arr1 - arr2

# Print the arrays and the result
print("Array 1 (sequential integers from 10 to 1):", arr1)
print("Array 2 (integers from 1 to 10):", arr2)
print("Result of element-wise subtraction:", result)

Array 1 (sequential integers from 10 to 1): [10  9  8  7  6  5  4  3  2  1]
Array 2 (integers from 1 to 10): [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [55]:
# Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
# Create arr1 with random integers (let's assume 5 elements as an example)
arr1 = np.random.randint(1, 10, size=5)

# Create arr2 with integers from 1 to 5
arr2 = np.array([1, 2, 3, 4, 5])

# Perform element-wise multiplication
result = arr1 * arr2

# Print the arrays and the result
print("Array 1 (random integers):", arr1)
print("Array 2 (integers from 1 to 5):", arr2)
print("Result of element-wise multiplication:", result)

Array 1 (random integers): [4 6 9 4 8]
Array 2 (integers from 1 to 5): [1 2 3 4 5]
Result of element-wise multiplication: [ 4 12 27 16 40]


In [56]:
# Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
# Generate arr1 with even integers from 2 to 10
arr1 = np.array([2, 4, 6, 8, 10])

# Generate arr2 with integers from 1 to 5
arr2 = np.array([1, 2, 3, 4, 5])

# Perform element-wise division
result = arr1 / arr2

# Print the arrays and the result
print("Array 1 (even integers from 2 to 10):", arr1)
print("Array 2 (integers from 1 to 5):", arr2)
print("Result of element-wise division:", result)

Array 1 (even integers from 2 to 10): [ 2  4  6  8 10]
Array 2 (integers from 1 to 5): [1 2 3 4 5]
Result of element-wise division: [2. 2. 2. 2. 2.]


In [57]:
# Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
# Generate arr1 with integers from 1 to 5
arr1 = np.array([1, 2, 3, 4, 5])

# Generate arr2 with the same integers but reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation (arr1 raised to the power of arr2)
result = np.power(arr1, arr2)

# Print the arrays and the result
print("Array 1 (integers from 1 to 5):", arr1)
print("Array 2 (integers reversed):", arr2)
print("Result of exponentiation (arr1 raised to the power of arr2):", result)

Array 1 (integers from 1 to 5): [1 2 3 4 5]
Array 2 (integers reversed): [5 4 3 2 1]
Result of exponentiation (arr1 raised to the power of arr2): [ 1 16 27 16  5]


In [58]:
# Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_substring_occurrences(arr, substring):
    # Use a vectorized operation to check for the substring in each element of the array
    count = np.sum(np.char.find(arr, substring) != -1)
    return count

# Example array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Count occurrences of 'hello'
substring = 'hello'
result = count_substring_occurrences(arr, substring)

print(f"Occurrences of '{substring}':", result)

Occurrences of 'hello': 3


In [59]:
# Write a function that extracts uppercase characters from a NumPy array of strings.
def extract_uppercase_chars(arr):
    # Use vectorized operation to filter out uppercase characters from each string in the array
    uppercase_chars = np.array([''.join([char for char in string if char.isupper()]) for string in arr])
    return uppercase_chars

# Example array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
result = extract_uppercase_chars(arr)

print("Uppercase characters:", result)

Uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [60]:
# Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace to replace occurrences of old_substring with new_substring
    updated_array = np.char.replace(arr, old_substring, new_substring)
    return updated_array

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Replace occurrences of 'apple' with 'orange'
old_substring = 'apple'
new_substring = 'orange'
result = replace_substring(arr, old_substring, new_substring)

print("Updated Array:", result)

Updated Array: ['orange' 'banana' 'grape' 'pineorange']


In [61]:
# Write a function that concatenates strings in a NumPy array element-wise.
def concatenate_strings(arr):
    # Use np.char.add to concatenate strings element-wise
    concatenated_array = np.char.add(arr[:-1], arr[1:])
    return concatenated_array

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Concatenate strings element-wise
result = concatenate_strings(arr)

print("Concatenated Array:", result)

Concatenated Array: ['applebanana' 'bananagrape' 'grapepineapple']


In [62]:
# Write a function that finds the length of the longest string in a NumPy array.
def longest_string_length(arr):
    # Find the length of the longest string in the array
    lengths = np.char.str_len(arr)  # Get lengths of all strings in the array
    return np.max(lengths)  # Return the maximum length

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
longest_length = longest_string_length(arr)

print("Length of the longest string:", longest_length)

Length of the longest string: 9


In [63]:
# Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
# Generate a dataset of 100 random integers between 1 and 1000
data = np.random.randint(1, 1001, size=100)

# Calculate mean, median, variance, and standard deviation
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

# Display the results
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")

Mean: 512.68
Median: 485.0
Variance: 86501.3976
Standard Deviation: 294.1111993787384


In [65]:
# Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

data = np.random.uniform(1, 100, size=50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

# Display the results
print(f"Generated Data: {data}")
print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")

Generated Data: [60.98234104 17.0766175  53.06133663 66.80971329 49.2736374  14.54123712
 31.34965508 85.50571758 60.6667105  70.68338368 63.54935273 43.78198496
 44.90644185 48.3091945  61.61345144 86.39492772 16.9519893  27.9145477
 33.90595379 60.54200864 10.15431746 40.27469975 57.35551279 25.51969071
  3.07275812 14.96871992 81.34082922 88.29084696  1.48102031 41.25697958
 16.0470926  16.18878124 53.72583415 52.53067651  2.76530062 70.80799878
 60.1075814  55.00250521 72.8566761  84.46359121 59.95765819 24.62798745
 72.22684621 83.97441571 61.20584595  2.30509563 85.62727356 91.43139607
 67.82580573  8.8662295 ]
25th Percentile: 24.85091326921926
75th Percentile: 67.57178262297862


In [66]:
# Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
array1 = np.random.rand(10) * 100  # Random numbers between 0 and 100
array2 = np.random.rand(10) * 100  # Random numbers between 0 and 100

# Compute the correlation coefficient
correlation_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient
correlation_coefficient = correlation_matrix[0, 1]

# Display the results
print(f"Array 1: {array1}")
print(f"Array 2: {array2}")
print(f"Correlation Coefficient: {correlation_coefficient}")

Array 1: [20.81990938  9.32224452 98.6317038  53.32066678 23.5747156  44.5454537
 12.06675942 16.40512148 92.94285061  6.01725918]
Array 2: [45.43261973 58.5290807  98.68201479 48.52171684 16.11681043 93.99902739
  9.37040125 34.42993115 27.28037846 84.28027932]
Correlation Coefficient: 0.26526028010516933


In [67]:
# Create two matrices and perform matrix multiplication using NumPy's `dot` function.
# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

# Display the matrices and result
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Multiplication Result:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix Multiplication Result:
[[ 58  64]
 [139 154]]


In [68]:
# Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
# Generate an array of 50 random integers between 10 and 1000
random_array = np.random.randint(10, 1000, size=50)

# Calculate the required percentiles
tenth_percentile = np.percentile(random_array, 10)
median = np.percentile(random_array, 50)
ninetieth_percentile = np.percentile(random_array, 90)
first_quartile = np.percentile(random_array, 25)
third_quartile = np.percentile(random_array, 75)

# Display the results
print("Generated Array:", random_array)
print(f"10th Percentile: {tenth_percentile}")
print(f"Median (50th Percentile): {median}")
print(f"90th Percentile: {ninetieth_percentile}")
print(f"First Quartile (25th Percentile): {first_quartile}")
print(f"Third Quartile (75th Percentile): {third_quartile}")

Generated Array: [849 189 725 231 579 330 608 532 183 301  17 911 109 602 900 703 363 582
 856 765 217 330 769 158 652 206 795 229 256  87 185 554 861 447 109 232
  43 823 304 632  86 228 914 657  48 486 444 449 639 160]
10th Percentile: 106.80000000000001
Median (50th Percentile): 445.5
90th Percentile: 849.7
First Quartile (25th Percentile): 208.75
Third Quartile (75th Percentile): 655.75


In [69]:
# Create a NumPy array of integers and find the index of a specific element.
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Define the element whose index you want to find
element_to_find = 40

# Find the index of the specific element
try:
    index = np.where(arr == element_to_find)[0][0]  # Find indices where the condition is True
    print(f"The index of {element_to_find} is {index}.")
except IndexError:
    print(f"The element {element_to_find} is not in the array.")

The index of 40 is 3.


In [70]:
# Generate a random NumPy array and sort it in ascending order.
random_array = np.random.randint(1, 101, size=10)  # Array of size 10 with values between 1 and 100

# Sort the array in ascending order
sorted_array = np.sort(random_array)

# Print the original and sorted arrays
print("Original Array:", random_array)
print("Sorted Array:", sorted_array)

Original Array: [30 66 55 53 39 33 63 28 65 65]
Sorted Array: [28 30 33 39 53 55 63 65 65 66]


In [71]:
# Filter elements >20  in the given NumPy array.
# Given array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_array = arr[arr > 20]

# Print the result
print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_array)

Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [72]:
# Filter elements which are divisible by 3 from a given NumPy array.
# Given array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
divisible_by_3 = arr[arr % 3 == 0]

# Print the result
print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", divisible_by_3)

Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


In [73]:
# Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# Given array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 (inclusive)
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Print the result
print("Original Array:", arr)
print("Filtered Array (elements ≥ 20 and ≤ 40):", filtered_arr)

Original Array: [10 20 30 40 50]
Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


In [74]:
# For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
# Given array
arr = np.array([1, 2, 3])

# Check byte order using dtype.byteorder
byte_order = arr.dtype.byteorder

# Print the result
if byte_order == "=":
    print("The array uses the native byte order of the system.")
elif byte_order == ">":
    print("The array uses big-endian byte order.")
elif byte_order == "<":
    print("The array uses little-endian byte order.")
else:
    print("Unknown byte order.")

The array uses the native byte order of the system.


In [75]:
# For the given NumPy array, perform byte swapping in place using `byteswap()`.
# Given array of int32 type
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

# Print the result
print("Array after byte swapping:", arr)

Array after byte swapping: [16777216 33554432 50331648]


In [76]:
# For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
# Given array of int32 type
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print original and swapped arrays
print("Original array:", arr)
print("Swapped array:", swapped_arr)

Original array: [1 2 3]
Swapped array: [16777216 33554432 50331648]


In [79]:
# For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
import sys  # Importing the sys module
# Given array of int32 type
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's endianness
if sys.byteorder == 'little':
    # If the system is little-endian, swap to big-endian
    swapped_arr = arr.newbyteorder('>')
else:
    # If the system is big-endian, swap to little-endian
    swapped_arr = arr.newbyteorder('<')

# Print original and swapped arrays
print("Original array:", arr)
print("Swapped array:", swapped_arr)

Original array: [1 2 3]
Swapped array: [16777216 33554432 50331648]


In [80]:
# For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
# Given array of int32 type
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
if arr.dtype.byteorder != sys.byteorder:
    print("Byte swapping is necessary.")
    swapped_arr = arr.byteswap()
    print("Array after byte swapping:", swapped_arr)
else:
    print("No byte swapping is necessary.")
    print("Original array:", arr)

Byte swapping is necessary.
Array after byte swapping: [16777216 33554432 50331648]


In [81]:
# Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
# Create an array arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in the copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original array (arr1):", arr1)
print("Modified copy array (copy_arr):", copy_arr)

Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [82]:
# Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
# Create a 3x3 matrix with random integers between 1 and 100
matrix = np.random.randint(1, 101, size=(3, 3))

# Extract a slice (view) from the matrix
view_slice = matrix[1:, 1:]

# Modify an element in the view_slice
view_slice[0, 0] = 999

# Observe changes in the matrix and view_slice
print("Original matrix after modifying view_slice:")
print(matrix)
print("\nModified view_slice:")
print(view_slice)

Original matrix after modifying view_slice:
[[ 75  14  88]
 [ 98 999  51]
 [ 68  64  33]]

Modified view_slice:
[[999  51]
 [ 64  33]]


In [83]:
# Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
# Create array_a with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice (view) from array_a
view_b = array_a[1:, 1:]

# Broadcast the addition of 5 to view_b
view_b += 5

# Observe changes in the original array_a and view_b
print("Original array_a after modifying view_b:")
print(array_a)
print("\nModified view_b:")
print(view_b)

Original array_a after modifying view_b:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]

Modified view_b:
[[10 11]
 [13 14]
 [16 17]]


In [84]:
# Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
# Create orig_array with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view of orig_array with shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 1] = 99

# Check changes in both orig_array and reshaped_view
print("Original orig_array after modifying reshaped_view:")
print(orig_array)
print("\nModified reshaped_view:")
print(reshaped_view)

Original orig_array after modifying reshaped_view:
[[ 1 99  3  4]
 [ 5  6  7  8]]

Modified reshaped_view:
[[ 1 99]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [85]:
# Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`
# Create a NumPy array 'data' with random integers (let's set a random seed for reproducibility)
np.random.seed(42)
data = np.random.randint(1, 10, size=(3, 4))

# Extract a copy of elements greater than 5 from 'data'
data_copy = data[data > 5].copy()

# Modify an element in 'data_copy'
data_copy[0] = 100

# Check if modifying 'data_copy' affects 'data'
print("Original 'data' array:")
print(data)
print("\nModified 'data_copy' array:")
print(data_copy)

Original 'data' array:
[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]]

Modified 'data_copy' array:
[100   8   7   7   8   8   8]


In [86]:
# Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
# Create two 2D matrices A and B with random integers
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

# Perform addition and subtraction operations
addition_result = A + B
subtraction_result = A - B

# Display the matrices and results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

print("\nAddition result (A + B):")
print(addition_result)

print("\nSubtraction result (A - B):")
print(subtraction_result)

Matrix A:
[[3 6 5]
 [2 8 6]
 [2 5 1]]

Matrix B:
[[6 9 1]
 [3 7 4]
 [9 3 5]]

Addition result (A + B):
[[ 9 15  6]
 [ 5 15 10]
 [11  8  6]]

Subtraction result (A - B):
[[-3 -3  4]
 [-1  1  2]
 [-7  2 -4]]


In [88]:
# Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
# Create matrices C (3x2) and D (2x4) with random integers
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

# Perform matrix multiplication (dot product)
result = np.dot(C, D)

# Display the matrices and the result
print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

print("\nMatrix multiplication result (C x D):")
print(result)

Matrix C (3x2):
[[3 7]
 [5 9]
 [7 2]]

Matrix D (2x4):
[[4 9 2 9]
 [5 2 4 7]]

Matrix multiplication result (C x D):
[[ 47  41  34  76]
 [ 65  63  46 108]
 [ 38  67  22  77]]


In [89]:
# Create a matrix `E` and find its transpose.
# Create a matrix E (3x2) with random integers
E = np.random.randint(1, 10, size=(3, 2))

# Find the transpose of matrix E
E_transpose = E.T

# Display the original matrix and its transpose
print("Matrix E:")
print(E)

print("\nTranspose of Matrix E:")
print(E_transpose)

Matrix E:
[[8 3]
 [1 4]
 [2 8]]

Transpose of Matrix E:
[[8 1 2]
 [3 4 8]]


In [90]:
# Generate a square matrix `F` and compute its determinant.
# Generate a square matrix F (e.g., 3x3) with random integers
F = np.random.randint(1, 10, size=(3, 3))

# Compute the determinant of matrix F
det_F = np.linalg.det(F)

# Display the matrix and its determinant
print("Matrix F:")
print(F)

print("\nDeterminant of Matrix F:")
print(det_F)

Matrix F:
[[4 2 6]
 [6 4 6]
 [2 2 4]]

Determinant of Matrix F:
15.999999999999998


In [91]:
# Create a square matrix `G` and find its inverse.
# Generate a square matrix G (e.g., 3x3) with random integers
G = np.random.randint(1, 10, size=(3, 3))

# Compute the inverse of matrix G
# Note: The matrix must be non-singular (its determinant should not be 0)
try:
    inv_G = np.linalg.inv(G)
    print("Matrix G:")
    print(G)
    print("\nInverse of Matrix G:")
    print(inv_G)
except np.linalg.LinAlgError:
    print("Matrix G is singular and cannot be inverted.")

Matrix G:
[[8 7 9]
 [8 5 2]
 [5 8 9]]

Inverse of Matrix G:
[[ 0.19463087  0.06040268 -0.20805369]
 [-0.41610738  0.18120805  0.37583893]
 [ 0.26174497 -0.19463087 -0.10738255]]
